Adding image fresnel zone
microshare/microshare.github.io pull request #211
Opened 2021-06-18 12:47 UTC by tidelbo

2021-06-18 14:08 UTC, JulienBardin requested changes
@tidelbo some edits are need otherwise good to go

2021-06-18 14:08 UTC, JulienBardin commented on docs/2/installer/lorawan/gateway-installations/outdoor-istation.md
> +{% include image.html width=400 url="/assets/img/LoRaWAN Device pictures/Without text.jpg" description="LoRaWan Technology" %}
no space, it should be dashes and lower case. Take a look at the other images in the same page

2021-06-18 14:08 UTC, JulienBardin commented on docs/2/installer/lorawan/gateway-installations/outdoor-istation.md
> +{% include image.html width=400 url="/assets/img/LoRaWAN Device pictures/Without text.jpg" description="LoRaWan Technology" %}
no space, it should be dashes and lower case. Take a look at the other images in the same page

2021-06-18 15:20 UTC, JulienBardin commented
you use two time the same image and you don't use : assets/img/LoRaWAN Device pictures/Without text.jpg

2021-06-18 15:58 UTC, tidelbo commented
> you use two time the same image and you don't use : assets/img/LoRaWAN Device pictures/Without text.jpg

Yes is is two time the same image on purpose. And I changed the image that is why it is not the same name anymore

2021-06-18 17:39 UTC, JulienBardin commented
Can you delete the image not used ?

2021-06-21 06:27 UTC, tidelbo commented
> Can you delete the image not used ?

It is done.

2021-06-21 07:24 UTC, merged