Jtantum documentation additions
microshare/microshare.github.io pull request #230
Opened 2023-03-24 20:52 UTC by jtantum

Hey Julien,  here are my documentation additions for the Admin - User Management new doc page. Its been a bit since I've worked on documentation, so I'm sure there are a few things I will have to clean up/add. Let me know what you think!

2023-03-27 10:13 UTC, JulienBardin requested changes
Only a few changes needed, and also adding the page to the menu by doing so : 
https://github.com/microshare/microshare.github.io#e-add-a-page-to-the-left-sidebar-menu

2023-03-27 10:13 UTC, JulienBardin commented on assets/img/admin/Managing Users 1 Enable-Disable User.jpg
Can you remove the spaces in the name

2023-03-27 10:13 UTC, JulienBardin commented on docs/2/admin/admin-management/user-management
> +{% include image.html url=" /assets/img/admin/Managing_Users_Roles1.jpg" description="Banner" %}
maybe specify that for now this is not really used ? but this will have an impact in the future ?

2023-03-28 20:24 UTC, jtantum commented on assets/img/admin/Managing Users 1 Enable-Disable User.jpg
removed space from image file name - assets/img/admin/Managing_Users_Enable_Disable1.jpg

2023-03-28 20:24 UTC, jtantum commented on docs/2/admin/admin-management/user-management
> +{% include image.html url=" assets/img/admin/Managing Users 1 Enable-Disable User.jpg" description="Banner" %}
removed file name spaces and updated URL path - assets/img/admin)/Managing_Users_Enable_Disable1.jpg

2023-03-28 21:05 UTC, jtantum commented
Hey @JulienBardin thanks for reviewing. I have made the changes mentioned. Let me know if there is anything else to edit/add!

2023-03-30 14:26 UTC, JulienBardin approved these changes
LGTM

2023-03-30 14:26 UTC, merged