Creating Custom Incidents doc
microshare/microshare.github.io pull request #260
Opened 2024-08-08 10:29 UTC by jotawarsd

Documentation to create custom incidents not related to any sensor or sensor location using share api in postman

2024-08-27 08:17 UTC, JulienBardin requested changes
1) we said we should change the screenshots to not have staff events but eitheir some leak or "customs" events.

2) I think the examples of json events to produce should show the capability of adding additionnal custom events / maybe even custom "alert" but not sure about the custom "solution", I would keep for now the solution has to be either alert (rodent type of solution) or clean (bathroom type of solution)

3) We also discussed about the location tags in the screenshots to take something more random/custom as these one are a copy of customer tags I believe.

4) make the link with the other doc page and explain that the bundler has to be configured. 

5)  put links to understand the alerts/incident process at the top

2024-08-27 10:55 UTC, JulienBardin requested changes
we are missing the information about the recType and how to use a custom recType if needed - requiring a custom bundler.

2024-08-29 08:48 UTC, JulienBardin requested changes

2024-08-29 08:55 UTC, jotawarsd commented on docs/2/technical/microshare-platform-advanced/creating-custom-incidents.md
> +The dafault recType for alerts is io.microshare.event.alert.
The . after alert was supposed to be a full stop :) 
But I can see how that can be misleading, so I'll remove that :>

2024-08-29 09:36 UTC, jotawarsd commented on docs/2/technical/microshare-platform-advanced/creating-custom-incidents.md
> +  "solution": "clean"
Okay. So, should I add any explanations pertaining to this?

2024-08-29 14:00 UTC, JulienBardin requested changes
just the recTypes in the screenshots are confusing

2024-09-02 09:45 UTC, JulienBardin approved these changes
LGTM - we will update with feedback and testings + we are working on options with Lisa for the "customs events"

2024-09-02 09:45 UTC, merged